---
#
# this can be included in a playbook via
# vars_files:
#   - server-configs.yml
#

# virtual machine resource profiles
# structured data complex dictionary
#
# vm_specs[‘vm_small’ ].cpu, .ram
# vm_specs[‘vm_medium’].cpu, .ram
# vm_specs[‘vm_large’ ].cpu, .ram
#
# vm_profile: “vm_small”
# vm_specs[vm_profile ].cpu, .ram

vm_profile: vm_small		# guaranteed default value
vm_specs:
  vm_small:
    cpu: 1
    ram: 2
  vm_medium:
    cpu: 2
    ram: 4
  vm_large:
    cpu: 4
    ram: 8

# operating system specific specifications
# structured data complex dictionary
#
# os_specs[‘redhat7’].guest, .scsi, .nic, .image
# os_specs[‘ubuntu’ ].guest, .scsi, .nic, .image
# os_specs[‘windows’].guest, .scsi, .nic, .image
#
# os_profile: “redhat7”
# os_specs[os_profile].guest,.scsi, .nic, .image

os_profile: redhat7		# guaranteed default value
os_specs:
  redhat7:
    guest: rhel7_64bit
    scsi: paravirtual
    nic: vmxnet3
    image: redhat7.iso
  ubuntu:
    guest: ubuntu64bit
    scsi: paravirtual
    nic: vmxnet3
    image: ubuntu18.iso
  windows:
    guest_id: windows9server64bit
    scsi: lsilogicsas
    nic: e1000e
    image: windows16.iso

# filesystems specifications
# structured dictionary of JSON lists
#
# fs_specs[‘general’]
# fs_specs[‘oracle’ ]
# fs_specs[‘mysql’  ]
# fs_specs[‘web’    ]
# fs_specs[‘mssql’  ]
#
# fs_profile: “oracle”
# fs_specs[fs_profile]

fs_profile: general
fs_specs:
  general: [
    { size_gb: 60, type: thin, datastore: somewhere }	# /
  ]
  oracle: [
    { size_gb: 60, type: thin, datastore: somewhere }, 	# /
    { size_tb:  1, type: thin, datastore: somewhere }, 	# /apps
    { size_tb:  1, type: thin, datastore: somewhere } 	# /data
  ]
  mysql: [
    { size_gb: 60, type: thin, datastore: somewhere }, 	# /
    { size_tb:  1, type: thin, datastore: somewhere }, 	# /apps
    { size_tb:  1, type: thin, datastore: somewhere } 	# /data
  ]
  web: [
    { size_gb: 60, type: thin, datastore: somewhere }, 	# /
    { size_gb: 100, type: thin, datastore: somewhere } 	# /sites
  ]
  mssql: [
    { size_gb:  60, type: thin, datastore: somewhere }, # C:
    { size_gb: 100, type: thin, datastore: somewhere }, # D:
    { size_gb: 100, type: thin, datastore: somewhere }, # E:
    { size_gb: 100, type: thin, datastore: somewhere }, # F:
    { size_gb: 100, type: thin, datastore: somewhere }, # G:
    { size_gb: 100, type: thin, datastore: somewhere }, # H:
    { size_gb: 100, type: thin, datastore: somewhere }  # I:
  ]